api_platform:
    # The title of the API.
    title: 'API WEB SERVICE OCR'

    # The description of the API.
    description: 'API WEB SERVICE BileMo'

    # The version of the API.
    version: '1.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false # desactivation de la pagination
            items_per_page: 10 # nombre d'éléments par défaut

